name: Release Test

on:
  push:
    branches:
      - test-release # Your test branch
  workflow_dispatch: # Manual trigger

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: core-linux-amd64
            binary_path: build/native/nativeCompile/core
          - os: windows-latest
            asset_name: core-windows-amd64.exe
            binary_path: build/native/nativeCompile/core.exe
          - os: macos-14
            asset_name: core-macos-aarch64
            binary_path: build/native/nativeCompile/core
          - os: macos-latest
            asset_name: core-macos-x86_64
            binary_path: build/native/nativeCompile/core

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: "graalvm-community"
          java-version: "24"

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Get test version
        id: get_version
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Get current version without creating a tag
          CURRENT_VERSION=$(./gradlew currentVersion -q -Prelease.quiet | tail -n 1)
          TEST_VERSION="test-${CURRENT_VERSION}-${{ github.run_number }}"
          echo "VERSION=${TEST_VERSION}" >> $GITHUB_ENV
          echo "VERSION=${TEST_VERSION}" >> $GITHUB_OUTPUT
          echo "Test version: ${TEST_VERSION}"

      - name: Build native image
        run: ./gradlew nativeBuild

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION || format('test-{0}', github.run_number) }}
          files: ${{ matrix.binary_path }}
          asset_name: ${{ matrix.asset_name }}
          prerelease: true # Mark as pre-release
          draft: true # Create as draft
          body: |
            🧪 **Test Release**

            This is a test release from branch: ${{ github.ref_name }}
            Build number: ${{ github.run_number }}

            ⚠️ This is not a production release - for testing purposes only.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
